### PR TITLE
Create Is Retroactive compatible with an M1 Mac running Big Sur?

### PR DESCRIPTION
**Pull request by Lamision11-2019**
I've read that Retroactive is compatible with Big Sur, but I've also read that the new M1 Macs won't work with some earlier apps due to changes in the M1.  Will Retroactive allow me to continue using Aperture running Big Sur on an M1 MacBook Air?

### CODE REVIEW

**Comment by k9malinda** [comment]
can't launch Retroactive on M1 / 12.1 - is it not going to work?

**Comment by pgib** [comment]
Retroactive worked for me on my M1 Mac mini running Monterey 12.1. Aperture seems to load fine now.

image

**Comment by k9malinda** [comment]
Hi Patrick, 

Thanks for the note, I can not get iTunes / iPhoto to load.  Sometimes it will load then it crashes. 

Advice?

malinda julien

**Comment by paparaha4** [comment]
ok

**Comment by markd1970** [comment]
> Retroactive worked for me on my M1 Mac mini running Monterey 12.1. Aperture seems to load fine now.
> 
> image

Are you able to log into iCloud Photos threw Aperture settings? I'm not able to.

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).

**Pull request closed without merging**
